import 'package:flutter/material.dart';
import 'package:sparky/component/text/common_text.dart';

class DisclaimerScreen extends StatelessWidget {
  const DisclaimerScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const CommonText(
          text: 'Disclaimer',
          fontSize: 20,
          fontWeight: FontWeight.bold,
        ),
      ),
      body: const SingleChildScrollView(
        padding: EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [

            Text(
              'Disclaimer & Terms of Use',
              style: TextStyle(
                fontSize: 22,
                fontWeight: FontWeight.bold,
                color: Colors.white,
              ),
            ),
            SizedBox(height: 8),
            Text(
              'IMPORTANT: PLEASE READ CAREFULLY. This Disclaimer is incorporated into and forms a part of the TrinFJH Tech Solutions End User License Agreement (EULA).',
              style: TextStyle(
                fontSize: 13,
                color: Colors.white60,
                height: 1.7,
                fontStyle: FontStyle.italic,
              ),
            ),

            SizedBox(height: 20),

            // Section 1
            Text(
              '1. Qualified Professional Use Only',
              style: TextStyle(
                fontSize: 16,
                fontWeight: FontWeight.bold,
                color: Colors.white,
              ),
            ),
            SizedBox(height: 8),
            Text(
              'This application is intended solely for use by qualified electrical professionals, including but not limited to properly licensed electrical contractors, electricians, and individuals with equivalent technical training and documented experience.',
              style: TextStyle(
                fontSize: 14,
                color: Colors.white60,
                height: 1.7,
              ),
            ),

            SizedBox(height: 20),

            // Section 2
            Text(
              '2. Reference and Estimation Only',
              style: TextStyle(
                fontSize: 16,
                fontWeight: FontWeight.bold,
                color: Colors.white,
              ),
            ),
            SizedBox(height: 8),
            Text(
              'The calculations, tools, and information provided by Sparky Toolbox are offered for general reference and preliminary estimation purposes only. They are not a substitute for professional judgment, proper field training, or a full understanding of underlying electrical principles.',
              style: TextStyle(
                fontSize: 14,
                color: Colors.white60,
                height: 1.7,
              ),
            ),

            SizedBox(height: 20),

            // Section 3
            Text(
              '3. No Sole Reliance',
              style: TextStyle(
                fontSize: 16,
                fontWeight: FontWeight.bold,
                color: Colors.white,
              ),
            ),
            SizedBox(height: 8),
            Text(
              'Users must have a complete and independent understanding of how all calculations are performed and agree not to rely solely on the results generated by this app. All outputs must be reviewed, verified, and validated by the user against physical code books and manufacturer data before being applied to any real-world installation, design, or energized system.',
              style: TextStyle(
                fontSize: 14,
                color: Colors.white60,
                height: 1.7,
              ),
            ),

            SizedBox(height: 20),

            // Section 4
            Text(
              '4. User Responsibility',
              style: TextStyle(
                fontSize: 16,
                fontWeight: FontWeight.bold,
                color: Colors.white,
              ),
            ),
            SizedBox(height: 8),
            Text(
              'It is the user\'s sole responsibility to:\n\n'
                  '• Follow all manufacturer instructions, specifications, and installation requirements.\n'
                  '• Comply with all local, state, and federal codes, regulations, and supplemental amendments.\n'
                  '• Possess a working knowledge of nationally recognized electrical safety standards and to consult applicable code books directly to verify all work.\n'
                  '• Ensure that all work is performed safely, legally, and in accordance with the standards of the Authority Having Jurisdiction (AHJ).',
              style: TextStyle(
                fontSize: 14,
                color: Colors.white60,
                height: 1.7,
              ),
            ),

            SizedBox(height: 20),

            // Section 5
            Text(
              '5. Assumption of Risk & Liability',
              style: TextStyle(
                fontSize: 16,
                fontWeight: FontWeight.bold,
                color: Colors.white,
              ),
            ),
            SizedBox(height: 8),
            Text(
              'TrinFJH Tech Solutions assumes no responsibility or liability for errors, omissions, misuse, misinterpretation, or outcomes resulting from the use of this app. Electrical work is inherently dangerous. Use of this application constitutes acknowledgment and acceptance of these terms and the full Limitation of Liability found in the EULA.',
              style: TextStyle(
                fontSize: 14,
                color: Colors.white60,
                height: 1.7,
              ),
            ),

            SizedBox(height: 30),
          ],
        ),
      ),
    );
  }
}