import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:sparky/utils/app_snackbar.dart';

import '../../../../component/button/common_button.dart';
import '../../../../component/text/common_text.dart';
import '../../../../config/route/app_routes.dart';
import '../../../../services/storage/storage_services.dart';
import '../../../../utils/constants/app_colors.dart';
import '../../../../utils/extensions/extension.dart';

List<String> _list = [
  'Follow all manufacturer instructions, specifications, and installation requirements.',
  'Comply with all local, state, and federal codes, regulations, and amendments.',
  'Possess a working knowledge of the National Electrical Code (NEC) and consult the NEC directly to verify all work.',
  'Ensure that all work is performed safely, legally, and in accordance with applicable standards.',
];

class DisclaimerScreen extends StatefulWidget {
  const DisclaimerScreen({super.key});

  @override
  State<DisclaimerScreen> createState() => _DisclaimerScreenState();
}

class _DisclaimerScreenState extends State<DisclaimerScreen> {
  bool _value = false;

  void _onChanged(bool? value) {
    setState(() {
      _value = value!;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const CommonText(
                text: 'Disclaimer & Terms of Use',
                fontSize: 20,
                fontWeight: FontWeight.w600,
                textAlign: TextAlign.start,
                maxLines: 10,
              ),

              const CommonText(
                text:
                    '\nThis application is intended solely for use by qualified electrical professionals, including but not limited to properly licensed C-10 electrical contractors, electricians, and individuals with equivalent training and experience.',
                maxLines: 10,
                textAlign: TextAlign.start,
              ),

              const CommonText(
                text:
                    '\nThe calculations, tools, and information provided by this app are offered for general reference and preliminary estimation purposes only. They are not a substitute for professional judgment, proper training, or a full understanding of the underlying electrical principles and calculations.',
                maxLines: 10,
                textAlign: TextAlign.start,
              ),

              const CommonText(
                text:
                    '\nUsers of this app must have a complete and independent understanding of how all calculations are performed and agree not to rely solely on the results generated by this app. All outputs should be reviewed, verified, and validated by the user before being applied to any real-world installation or design.\n',
                maxLines: 10,
                textAlign: TextAlign.start,
              ),

              const CommonText(
                text: 'It is the user’s responsibility to:',
                textAlign: TextAlign.start,
                fontWeight: FontWeight.bold,
              ),

              8.height,

              ...List.generate(_list.length, (index) {
                final item = _list[index];
                return Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Container(
                      height: 8,
                      width: 8,
                      margin: const EdgeInsets.symmetric(
                        horizontal: 10,
                      ).copyWith(top: 8),
                      decoration: const BoxDecoration(
                        color: Colors.black,
                        shape: BoxShape.circle,
                      ),
                    ),
                    Expanded(
                      child: CommonText(
                        text: item,
                        textAlign: TextAlign.start,
                        maxLines: 10,
                        left: 10,
                      ),
                    ),
                  ],
                );
              }),

              const CommonText(
                text:
                    '\nThe developer and company assume no responsibility or liability for any errors, omissions, misuse, misinterpretation, or outcomes resulting from the use of this app. Use of this application constitutes acknowledgment and acceptance of these terms.',
                textAlign: TextAlign.start,
                maxLines: 10,
              ),
            ],
          ),
        ),
      ),
      persistentFooterButtons: [
        Column(
          children: [
            Row(
              children: [
                Checkbox(
                  value: _value,
                  onChanged: _onChanged,
                  fillColor: WidgetStateProperty.all(
                    _value ? AppColors.black : Colors.transparent,
                  ),
                ),
                const CommonText(text: 'I Agree'),
                const Spacer(),
                 const CommonText(
                  text: 'EULA  AGREEMENT',
                  right: 8,
                ),
              ],
            ),
            CommonButton(
              titleText: 'Accept',
              buttonRadius: 30,
              onTap: () {
                if (!_value) {
                  AppSnackbar.error(
                    title: 'Acceptance Required',
                    message: 'You must accept the Terms to continue.',
                  );
                  return;
                }
                LocalStorage.saveIsAgree(true);
                Get.offAllNamed(AppRoutes.home);
              },
            ),
          ],
        ),
      ],
      persistentFooterDecoration: const BoxDecoration(
        color: Colors.transparent,
      ),
    );
  }
}
